CREATE USER django WITH PASSWORD 'django';
CREATE DATABASE django;
GRANT ALL PRIVILEGES ON DATABASE django TO django;
ALTER DATABASE django OWNER TO django;
GRANT ALL ON SCHEMA public TO django;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO django;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO django;