# Generated by Django 5.0 on 2024-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rag',
            name='file',
            field=models.FileField(editable=False, upload_to='uploads/rag/'),
        ),
    ]
