# Generated by Django 5.0 on 2024-09-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_alter_rag_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rag',
            name='file',
            field=models.FileField(upload_to='uploads/rag/'),
        ),
    ]
